### ISSUE TITLE
Create new django app

### ISSUE THREAD

**Issue by gyusang** [wafflestudio18-5/team2-server#1]
- Create app
- Add requirements.txt
- Add CI

**Comment by gyusang** [comment]
#2

**Comment by Hank-Choi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Django project (wadium) 만들고 Commit](https://trello.com/c/z450fT87/25-django-project-wadium-%EB%A7%8C%EB%93%A4%EA%B3%A0-commit)
